### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by tamarefrat** [sarabuc/SayCookBook#11]

**Comment by ShiraSegal** [comment]
3.	שמירת נתונים \ אחסון - Persistence

תארו כיצד נשמרים נתונים של המערכת, אלו קבצים ייווצרו ומה יהיה המבנה שלהם (ייתכן שתצטרכו תרשים מחלקות נוסף). במקרה שאתם גם מתכננים בסיס נתונים רלאציוני, ספקו תכנון ראשוני של הטבלאות והקשרים ביניהן.

**Comment by Devorah1** [comment]
שלום, אני לא כ"כ מבינה את הסעיף הזה.
כי ה-
class diagram
חופף מאד. בכל אופן, אם זו הדרישה עשיתי את זה ידנית, ואני צריכה להעלות ממוחשב.
אם מישהי מבינה בדיוק מה ההבדל - אשמח שתסביר.

**Comment by ShiraSegal** [comment]
עשית מחלקות ושרטוט ה-DB?
או רק של ה-CLASS?

**Comment by Devorah1** [comment]
גם וגם (עם מעט שינויים), אני אקח אחריות גם על סעיף זה.

**Comment by Devorah1** [comment]
done
